parser: babel-eslint
extends: 'eslint:recommended'
plugins:
  - jest
  - react
env:
  browser: true
  jest/globals: true
  es6: true
globals:
  jsdom: false
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
